### PR TITLE
Deprecations fix on SF5

### PR DESCRIPTION
**Pull request by hracik**
Fixed 2 more deprecation notices on SF5.

### CODE REVIEW

**Comment by hracik** [comment]
I don't know how to make pull request with only the last commit, sorry.. first two commits you already merged in master.

**Comment by gremo** [comment]
Hi, thank you for contributing! Can you create a new PR with the right commits? I can't get the "first two commits you already merged in master".

Cheers

**Comment by gremo** [comment]
So just to be sure, you just need this commit: https://github.com/gremo/ZurbInkBundle/pull/11/commits/e7f1a62301eaf627960207bc68540ccd84c88542 right?

**Comment by hracik** [comment]
@gremo yes, the other two are in the previous PR I made :/

Problem is that I don't know how to add only one commit in the PR -- it automatically adds the other commits there as well.

**Pull request closed without merging**
